definitions:
  gin.H:
    additionalProperties: {}
    type: object
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  models.Entree:
    properties:
      created_at:
        description: |-
          The time the record was created at

          We override Gorm's CreatedAt field so we can set the gorm:"<-:create" directive,
          which prevents this field from being altered once the record is created
        type: string
      deleted_at:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: string
      option_name:
        type: string
      updated_at:
        type: string
    required:
    - option_name
    type: object
  models.HorsDoeuvres:
    properties:
      created_at:
        description: |-
          The time the record was created at

          We override Gorm's CreatedAt field so we can set the gorm:"<-:create" directive,
          which prevents this field from being altered once the record is created
        type: string
      deleted_at:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: string
      option_name:
        type: string
      updated_at:
        type: string
    required:
    - option_name
    type: object
  models.User:
    properties:
      created_at:
        description: |-
          The time the record was created at

          We override Gorm's CreatedAt field so we can set the gorm:"<-:create" directive,
          which prevents this field from being altered once the record is created
        type: string
      deleted_at:
        $ref: '#/definitions/gorm.DeletedAt'
      email:
        description: The user's email (must be unique); this field is an index.
        type: string
      entree_selection_id:
        description: The ID of the entree the user has selected; is null until the
          user makes a selection.
        type: string
      entreeSelection:
        $ref: '#/definitions/models.Entree'
      first_name:
        description: The user's first name.
        type: string
      hors_doeuvres_selection_id:
        description: The ID of the hors doeuvres the user has selected; is null until
          the user makes a selection.
        type: string
      horsDoeuvresSelection:
        $ref: '#/definitions/models.HorsDoeuvres'
      id:
        type: string
      is_going:
        description: Whether or not the user is attending.
        type: boolean
      last_name:
        description: The user's last name.
        type: string
      password:
        description: Either a hash of the user's password (when stored in the DB),
          or a plain-text representation of the password (plain-text version is never
          stored)
        type: string
      refresh_token:
        description: The user's auth refresh token.
        type: string
      role:
        description: The user's role, which can be "GUEST", "INVITEE" or "ADMIN".
          Defaults to "GUEST".
        type: string
      token:
        description: The user's auth token.
        type: string
      updated_at:
        type: string
    required:
    - email
    - first_name
    - last_name
    type: object
  models.UserInvitee:
    properties:
      created_at:
        description: |-
          The time the record was created at

          We override Gorm's CreatedAt field so we can set the gorm:"<-:create" directive,
          which prevents this field from being altered once the record is created
        type: string
      deleted_at:
        $ref: '#/definitions/gorm.DeletedAt'
      entree_selection_id:
        description: The ID of the entree the user has selected; is null until the
          user makes a selection.
        type: string
      entreeSelection:
        $ref: '#/definitions/models.Entree'
      first_name:
        description: The user's first name.
        type: string
      hors_doeuvres_selection_id:
        description: The ID of the hors doeuvres the user has selected; is null until
          the user makes a selection.
        type: string
      horsDoeuvresSelection:
        $ref: '#/definitions/models.HorsDoeuvres'
      id:
        type: string
      inviter:
        $ref: '#/definitions/models.User'
      inviter_id:
        type: string
      last_name:
        description: The user's last name.
        type: string
      updated_at:
        type: string
    required:
    - first_name
    - inviter_id
    - last_name
    type: object
  types.EntreeData:
    properties:
      entrees:
        items:
          $ref: '#/definitions/models.Entree'
        type: array
    type: object
  types.HorsDoeuvresData:
    properties:
      hors_doeuvres:
        items:
          $ref: '#/definitions/models.HorsDoeuvres'
        type: array
    type: object
  types.UserData:
    properties:
      users:
        items:
          $ref: '#/definitions/models.User'
        type: array
    type: object
  types.UserInviteeData:
    properties:
      users:
        items:
          $ref: '#/definitions/models.UserInvitee'
        type: array
    type: object
  types.UserLoginInput:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  types.UserSignupInput:
    properties:
      email:
        type: string
      first_name:
        type: string
      invite_code:
        type: string
      last_name:
        type: string
      password:
        type: string
    required:
    - email
    - first_name
    - invite_code
    - last_name
    - password
    type: object
  types.V1_API_RESPONSE_ENTREE:
    properties:
      data:
        $ref: '#/definitions/types.EntreeData'
      message:
        type: string
      status:
        type: integer
    type: object
  types.V1_API_RESPONSE_HORS_DOEUVRES:
    properties:
      data:
        $ref: '#/definitions/types.HorsDoeuvresData'
      message:
        type: string
      status:
        type: integer
    type: object
  types.V1_API_RESPONSE_USER_INVITEES:
    properties:
      data:
        $ref: '#/definitions/types.UserInviteeData'
      message:
        type: string
      status:
        type: integer
    type: object
  types.V1_API_RESPONSE_USERS:
    properties:
      data:
        $ref: '#/definitions/types.UserData'
      message:
        type: string
      status:
        type: integer
    type: object
info:
  contact: {}
paths:
  /entree:
    delete:
      description: Deletes an entree and returns a response to indicate success or
        failure
      parameters:
      - description: Entree ID
        format: uuid
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/types.V1_API_RESPONSE_ENTREE'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.V1_API_RESPONSE_ENTREE'
      summary: deletes an entree
      tags:
      - entrees
    post:
      consumes:
      - application/json
      description: Create a new entree and return the new record's data to the caller
      parameters:
      - description: The input entree data (only `option_name` is required)
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.Entree'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/types.V1_API_RESPONSE_ENTREE'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.V1_API_RESPONSE_ENTREE'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.V1_API_RESPONSE_ENTREE'
      summary: create entree
      tags:
      - entrees
  /entrees:
    get:
      description: Gets the selected entree for the given user ID (empty array if
        no selection has been made), or a list of all available entrees if no user
        ID is provided
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.V1_API_RESPONSE_ENTREE'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.V1_API_RESPONSE_ENTREE'
      security:
      - JWT: []
      summary: gets one or all entrees
      tags:
      - entrees
  /horsdoeuvres:
    delete:
      description: Deletes an hors doeuvres and returns a response to indicate success
        or failure
      parameters:
      - description: Hors Doeuvres ID
        format: uuid
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/types.V1_API_RESPONSE_HORS_DOEUVRES'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.V1_API_RESPONSE_HORS_DOEUVRES'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.V1_API_RESPONSE_HORS_DOEUVRES'
      summary: deletes an hors doeuvres
      tags:
      - hors doeuvres
    get:
      description: Gets the selected hors doeuvres for the given user ID (empty array
        if no selection has been made), or a list of all available entrees if no user
        ID is provided
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.V1_API_RESPONSE_HORS_DOEUVRES'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.V1_API_RESPONSE_HORS_DOEUVRES'
      summary: gets one or all hors doeuvres
      tags:
      - hors doeuvres
    post:
      consumes:
      - application/json
      description: Creates an hors doeuvres and return the new record's data to the
        caller
      parameters:
      - description: The input hors doeuvres data (only `option_name` is required)
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.HorsDoeuvres'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/types.V1_API_RESPONSE_HORS_DOEUVRES'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.V1_API_RESPONSE_HORS_DOEUVRES'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.V1_API_RESPONSE_HORS_DOEUVRES'
      summary: creates an hors doeuvres
      tags:
      - hors doeuvres
  /invitee/{id}:
    delete:
      description: Deletes an invitee
      parameters:
      - description: User ID of the invitee to delete
        format: uuid
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.V1_API_RESPONSE_USER_INVITEES'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.V1_API_RESPONSE_USER_INVITEES'
      summary: deletes an invitee
      tags:
      - user invitee
  /login:
    post:
      consumes:
      - application/json
      description: Logs in a user and returns the user details for the user (if authentication
        is successful)
      parameters:
      - description: Log in details
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/types.UserLoginInput'
      - description: Anti CSRF token
        in: header
        name: X-CSRF-Token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/types.V1_API_RESPONSE_USERS'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.V1_API_RESPONSE_USERS'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.V1_API_RESPONSE_USERS'
      summary: Logs in a user
      tags:
      - auth
  /signup:
    post:
      consumes:
      - application/json
      description: Signs up a new user
      parameters:
      - description: Sign up details
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/types.UserSignupInput'
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/types.V1_API_RESPONSE_USERS'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.V1_API_RESPONSE_USERS'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.V1_API_RESPONSE_USERS'
      summary: Signs up a new user
      tags:
      - auth
  /user:
    delete:
      description: Deletes an user and returns a response to indicate success or failure
      parameters:
      - description: User ID
        format: uuid
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/types.V1_API_RESPONSE_USERS'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.V1_API_RESPONSE_USERS'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.V1_API_RESPONSE_USERS'
      summary: admin-only operation to delete a user
      tags:
      - user
    get:
      description: Gets user(s) by the ID(s) in the request query string, `?ids=`
      parameters:
      - description: user search by id
        format: uuid
        in: path
        name: ids
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.V1_API_RESPONSE_USERS'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.V1_API_RESPONSE_USERS'
      summary: gets user(s)
      tags:
      - user
    patch:
      consumes:
      - application/json
      description: Updates the logged in user with the given input
      parameters:
      - description: Post body
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/types.V1_API_RESPONSE_USERS'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.V1_API_RESPONSE_USERS'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.V1_API_RESPONSE_USERS'
      summary: updates the logged in user
      tags:
      - user
    post:
      consumes:
      - application/json
      description: Creates a user with the given input and returns an array of user
        objects, containing the newly-created user
      parameters:
      - description: The input user data (only `first_name`, `last_name` and `email`
          are required)
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/types.V1_API_RESPONSE_USERS'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.V1_API_RESPONSE_USERS'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.V1_API_RESPONSE_USERS'
      summary: admin-only operation to create a user
      tags:
      - user
  /user/{user_id}/entrees:
    get:
      description: Gets the selected entree for the given user ID (empty array if
        no selection has been made), or a list of all available entrees if no user
        ID is provided
      parameters:
      - description: User ID
        format: uuid
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.V1_API_RESPONSE_ENTREE'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.V1_API_RESPONSE_ENTREE'
      security:
      - JWT: []
      summary: gets one or all entrees
      tags:
      - entrees
  /user/{user_id}/horsdoeuvres:
    get:
      description: Gets the selected hors doeuvres for the given user ID (empty array
        if no selection has been made), or a list of all available entrees if no user
        ID is provided
      parameters:
      - description: User ID
        format: uuid
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.V1_API_RESPONSE_HORS_DOEUVRES'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.V1_API_RESPONSE_HORS_DOEUVRES'
      summary: gets one or all hors doeuvres
      tags:
      - hors doeuvres
  /user/{user_id}/add-invitee:
    post:
      description: Invites a user for ght given user
      parameters:
      - description: Inviting user ID
        format: uuid
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.V1_API_RESPONSE_USER_INVITEES'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.V1_API_RESPONSE_USER_INVITEES'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.V1_API_RESPONSE_USER_INVITEES'
      summary: invite a user
      tags:
      - user invitee
  /user/{user_id}/invitees:
    get:
      description: Gets invitee user data for users invited by the given inviter ID
      parameters:
      - description: Invitee search by inviting user ID
        format: uuid
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.V1_API_RESPONSE_USER_INVITEES'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.V1_API_RESPONSE_USER_INVITEES'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.V1_API_RESPONSE_USER_INVITEES'
      summary: gets invitees for user
      tags:
      - user invitee
swagger: "2.0"
