name: Test and coverage

on: [push, pull_request]

jobs:
  test-and-codecov:
    runs-on: ubuntu-latest
    env:
      SECRETS_CONTEXT: ${{ toJson(secrets) }}
    services:
        db:
          # Keep parity with whatever version we're using in docker-compose.yml
          image: postgres:16.3
          env:
            POSTGRES_DB: ${{ secrets.PGSQL_DBNAME }}
            POSTGRES_USER: ${{ secrets.PGSQL_USER }}
            POSTGRES_PASSWORD: ${{ secrets.PGSQL_PASSWORD }}
          # Set health checks to wait until postgres has started
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
          ports:
            - 9920:5432
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.22'
      - name: Run coverage
        run: |
          go test -tags=integration ./models -v  -race -coverprofile=coverage1.out -covermode=atomic
          go test -tags=unit ./models -v  -race -coverprofile=coverage2.out -covermode=atomic
          go test -tags=integration ./controllers -v  -race -coverprofile=coverage3.out -covermode=atomic
          go test -tags=unit ./controllers -v  -race -coverprofile=coverage4.out -covermode=atomic
        env:
          PGSQL_DBNAME: ${{ secrets.PGSQL_DBNAME }}
          PGSQL_USER: ${{ secrets.PGSQL_USER }}
          PGSQL_PASSWORD: ${{ secrets.PGSQL_PASSWORD }}
          PGSQL_PORT: ${{ secrets.PGSQL_PORT }}
          PGSQL_HOST: ${{ secrets.PGSQL_HOST }}
          PGSQL_TIMEZONE: ${{ secrets.PGSQL_TIMEZONE }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          files: ./coverage1.out,./coverage2.out,./coverage3.out,./coverage4.out
          fail_ci_if_error: true
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
