name: Load repository secrets

on:
  workflow_call:
    secrets:
      POSTGRES_DB:
        required: true
      POSTGRES_USER:
        required: true
      POSTGRES_PASSWORD:
        required: true
      PGSQL_PORT:
        required: true
      PGSQL_TIMEZONE:
        required: true
      PGSQL_DBNAME:
        required: true

jobs:
  load-secrets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        PGSQL_PORT: ${{ secrets.PGSQL_PORT }}
        PGSQL_TIMEZONE: ${{ secrets.PGSQL_TIMEZONE }}
        PGSQL_DBNAME: ${{ secrets.PGSQL_DBNAME }}
